info:
  component: Config Server
spring:
  profiles:
    active: vault
  application:
    name: configserver
#  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#  jmx:
#    default_domain: cloud.config.server
  cloud:
    config:
      server:
        vault:

server:
  port: 8888
management:
  context_path: /
